blank_issues_enabled: false
contact_links:
  - name: Report Sensitive Info
    url: https://juan-miii.github.io/
    about: Please report any private or security concerns here. Email provided in the link.
