# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and PR

on:
  schedule:
    - cron: '43 21 5 * *' # Runs at 21:43 UTC the fifth day of each month

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - name: Close stale issues and PRs
        uses: actions/stale@3a9db7e6a41a89f618792c92c0e97cc736e1b13f
        with:
          # Message config
          stale-issue-message: >
            This issue is stale because it has been inactive for 60 days. If it remains inactive for 7 more days, it will be closed. 
            Please comment or update the issue to keep it open.
          stale-pr-message: >
            This pull request is stale because it has been inactive for 60 days. If it remains inactive for 7 more days, it will be closed. 
            Please comment or update the PR to keep it open.
          close-issue-message: >
            This issue was closed due to inactivity. Feel free to reopen if necessary.
          close-pr-message: >
            This pull request was closed due to inactivity. Feel free to reopen if necessary.

          # Time config
          days-before-stale: 60
          days-before-close: 7

          # Tag config
          stale-issue-label: "Stale"
          stale-pr-label: "Stale"
          close-issue-label: "Closed"
          close-pr-label: "Closed"

          # Configuración adicional
          remove-stale-when-updated: true
          exempt-issue-labels: "pinned,important"
          exempt-pr-labels: "in-progress,wip"
          exempt-draft-pr: true
          enable-statistics: true
